global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-user-activity-log:9092']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-cache:6379']
