server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  #      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

  instance:
    lease-renewal-interval-in-seconds: ${EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS:10}
    lease-expiration-duration-in-seconds: ${EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS:30}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}


spring:
  application:
    name: Gateway-Service

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - Set-Cookie
              - Authorization
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: stock-websocket
          uri: lb:ws://stock-service
          predicates:
            - Path=/ws/upbit/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin
        - id: livechat-service
          uri: lb:ws://livechat-service
          predicates:
            - Path=/livechat-service/ws/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin
        - id: mvclivechat-service
          uri: lb:ws://mvclivechat-service
          predicates:
            - Path=/mvclivechat-service/ws/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post-service/**
          filters:
            - StripPrefix=1
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment-service/**
          filters:
            - StripPrefix=1
        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/activity-service/**
          filters:
            - StripPrefix=1
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stock-service/**
          filters:
            - StripPrefix=1
      default-filters:
        - name: JwtAuthFilter
          args:
            preLogger: true
            postLogger: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY:8385662e486a14c11b9dd23f7338d2696f88bb6074eb4f19bf9933ecd9673c09}