server:
  port: 8000




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
#      ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}


spring:
  application:
    name: Gateway-Service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post-service/**
          filters:
            - StripPrefix=1
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment-service/**
          filters:
            - StripPrefix=1
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: "Spring Cloud Gateway Global Filter"
            preLogger: true
            postLogger: true
        - name: JwtFilter



      globalcors:
        cors-configurations:
          '[/**]': # ?? ??? ?? CORS ??
            allowedOrigins:
              - "http://localhost:3000" # React ?????
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*" # ?? ?? ??
            allowCredentials: true # ?? ??


jwt:
  secret:
    key: ${JWT_SECRET_KEY:8385662e486a14c11b9dd23f7338d2696f88bb6074eb4f19bf9933ecd9673c09}
