server:
  port: 8082



spring:
  application:
    name: user-service

  profiles:
    active: default




  datasource:
    url: jdbc:mysql://localhost:3306/Stock_discussion
    username: root
    password: 4029
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



  jwt:
    secret:
      key: ${JWT_SECRET_KEY:8385662e486a14c11b9dd23f7338d2696f88bb6074eb4f19bf9933ecd9673c09}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # 환경 변수로 관리
    password: ${MAIL_PASSWORD} # 환경 변수로 관리
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


devtools:
  restart:
    enabled: true
  livereload:
    enabled: true
  additional-paths: src/main/java

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 20MB
    file-size-threshold: 2KB

mvc:
  cors:
    mappings:
      "/api/**":
        allowed-origins:
         - "http://localhost:8000"
         - "http://localhost:3000"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"
        allow-credentials: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
#      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

  instance:
    lease-renewal-interval-in-seconds: ${EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS:10}
    lease-expiration-duration-in-seconds: ${EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS:30}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
