server:
  port: 8091



spring:
  application:
    name: livechat-service

  profiles:
    active: default

  r2dbc:
    url: r2dbc:mysql://localhost:3306/chat_service?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password: password
    pool:
      enabled: true
      max-size: 20         # 최대 연결 수
      initial-size: 5      # 초기 연결 수


  management:
    metrics:
      export:
        influx:
          enabled: true
          uri: http://localhost:8086
          db: my-bucket
          user: myuser
          password: mypassword
          autoCreateDb: true

mvc:
  cors:
    mappings:
      "/api/**":
        allowed-origins:
         - "http://localhost:8000"
         - "http://localhost:3000"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"
        allow-credentials: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
#      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

  instance:
    lease-renewal-interval-in-seconds: ${EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS:10}
    lease-expiration-duration-in-seconds: ${EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS:30}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
