server:
  port: 8091



spring:
  application:
    name: livechat-service

  profiles:
    active: default

  user-service:
    url: http://localhost:8082

  r2dbc:
    url: r2dbc:mysql://localhost:3306/chat_service
    username: root
    password: 4029

    pool:
      enabled: true
      max-size: 20 # 연결 풀 최대 크기
      initial-size: 10 # 초기 연결 크기
      max-idle-time: 30s # 연결 유지 시간

#
#    flyway:
#      enabled: true
#      url: jdbc:mysql://localhost:3306/chat_service
#      user: root
#      password: 4029

    redis:
      host: localhost
      port: 6379





  management:
    metrics:
      export:
        influx:
          enabled: true
          uri: http://localhost:8086
          db: my-bucket
          user: myuser
          password: mypassword
          autoCreateDb: true

mvc:
  cors:
    mappings:
      "/api/**":
        allowed-origins:
         - "http://localhost:8000"
         - "http://localhost:3000"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"
        allow-credentials: true

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
#      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

  instance:
    lease-renewal-interval-in-seconds: ${EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS:10}
    lease-expiration-duration-in-seconds: ${EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS:30}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
