server:
  port: 8090



spring:
  application:
    name: mvclivechat-service

  profiles:
    active: default


  user-service:
    url: http://localhost:8082

  datasource:
    url: jdbc:mysql://localhost:3306/mvcchat_service?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password: 4029
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      default_schema: mvcchat_service
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 100  # 배치 처리 크기 설정
          order_inserts: true  # INSERT 순서 최적화
          order_updates: true  # UPDATE 순서 최적화

    chat:
      batch-interval: 1000  # 배치 주기 (밀리초)
      batch-size: 50        # 배치 크기


    redis:
      host: localhost
      port: 6379


mvc:
  cors:
    mappings:
      "/api/**":
        allowed-origins:
         - "http://localhost:8000"
         - "http://localhost:3000"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"
        allow-credentials: true

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
#      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

  instance:
    lease-renewal-interval-in-seconds: ${EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS:10}
    lease-expiration-duration-in-seconds: ${EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS:30}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
